# Generated by Django 2.2.7 on 2020-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_main', '0002_auto_20200928_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire_economic_data',
            name='area_expected',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
